name: vert_coord
dependencies:
  - python=3.10
  - pip
  - git
  - numpy
  - matplotlib
  - netcdf4
  - cfgrib
  - xarray
  - scipy
  - psyplot
  - psy-maps
  - ipython
  - ipdb
  - black
  - click
  - cartopy
  - ipykernel
  - pip:
    - git+https://github.com/C2SM/iconarray@backend_grid_improvements
